accordion-padding = 30
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[mode.main.binding]
alt-slash = 'layout tiles horizontal vertical'
alt-shift-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-tab = 'workspace-back-and-forth'
ctrl-alt-h = 'join-with left'
ctrl-alt-j = 'join-with down'
ctrl-alt-k = 'join-with up'
ctrl-alt-l = 'join-with right'
cmd-alt-h = 'move left'
cmd-alt-j = 'move down'
cmd-alt-k = 'move up'
cmd-alt-l = 'move right'
ctrl-alt-r = 'flatten-workspace-tree'
