" nimimal UI
set shortmess=aTIcFoOsSW showtabline=0 laststatus=0 
set noruler noshowcmd noshowmode
try
  set cmdheight=0
  " マクロ記録中は見えるようにする
  autocmd MikanAutoCmd CmdlineEnter,RecordingEnter * set cmdheight=1
  autocmd MikanAutoCmd CmdlineLeave,RecordingLeave * set cmdheight=0
  autocmd MikanAutoCmd BufWrite * lua vim.notify("save")
catch
  set cmdheight=1
endtry

set mouse= " マウスを無効化
set clipboard+=unnamed " クリップボード連携

let g:mapleader = "\<Space>"
let g:maplocalleader = 'm'

" Minimal keymap
" move window
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l
" split
nnoremap <Leader>- <Cmd>split<CR>
nnoremap <Leader>\ <Cmd>vsplit<CR>
nnoremap <Leader>n <Cmd>nohlsearch<CR>
" better visual
xnoremap r <C-v>
xnoremap v V
" stickey
nnoremap ; :
