[ -f "$HOME/.secrets.sh" ] && source "$HOME/.secrets.sh"

[ -f "/Users/solenoid/.ghcup/env" ] && source "/Users/solenoid/.ghcup/env"

export PATH="/opt/homebrew/opt/curl/bin:$PATH"
export PATH="$HOME/.local/nvim/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/scripts:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.deno/bin:$PATH"
export PATH="$HOME/.bun/bin:$PATH"
export PATH="$HOME/go/bin:$PATH"
export PATH="$PATH:$HOME/.pub-cache/bin"
export PATH="$PATH:$HOME/.maestro/bin"

# bun completions
[ -s "/Users/mikan/.bun/_bun" ] && source "/Users/mikan/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

WITHOUT_FISH=

if [[ $WITHOUT_FISH == "yes" ]]; then
  ## Emacs経由で起動した場合のみ
  if type starship &> /dev/null; then
    # eval "$(starship init zsh)"
  fi

  if type zoxide &> /dev/null; then
    eval "$(zoxide init zsh)"
  fi

  if test -d "$HOME/.cargo" &> /dev/null; then
    source "$HOME/.cargo/env"
  fi

  if test -d "$HOME/.deno" &> /dev/null; then
  fi

  if [[ -d "$HOME/.asdf" ]]; then
    source "$(brew --prefix asdf)/libexec/asdf.sh"
    source "$(brew --prefix asdf)/completions/asdf.bash"
  fi
  autoload -Uz compinit && compinit -C
else
  type fish &> /dev/null && exec fish
fi
