# This file has been generated by node2nix 1.11.1. Do not edit!

{
  nodeEnv,
  fetchurl,
  fetchgit,
  nix-gitignore,
  stdenv,
  lib,
  globalBuildInputs ? [ ],
}:

let
  sources = {
    "@actions/expressions-0.3.18" = {
      name = "_at_actions_slash_expressions";
      packageName = "@actions/expressions";
      version = "0.3.18";
      src = fetchurl {
        url = "https://registry.npmjs.org/@actions/expressions/-/expressions-0.3.18.tgz";
        sha512 = "LiZTqsWk5bwPUz2lkHpcf5sfbznBTlxxihPqjDndD+D+gJW6iOY0vxxztgqq6ft5rKY0WTXSOS+XJkJdqIqv/w==";
      };
    };
    "@actions/languageserver-0.3.18" = {
      name = "_at_actions_slash_languageserver";
      packageName = "@actions/languageserver";
      version = "0.3.18";
      src = fetchurl {
        url = "https://registry.npmjs.org/@actions/languageserver/-/languageserver-0.3.18.tgz";
        sha512 = "iq6e0hKeLy7CIZYFWLU8ZHLGC9mTjikXsmoUr57UquMJDFeCVPHihY32OGGyQLTAVvvQGGQEC6eTSKOaYItACQ==";
      };
    };
    "@actions/languageservice-0.3.18" = {
      name = "_at_actions_slash_languageservice";
      packageName = "@actions/languageservice";
      version = "0.3.18";
      src = fetchurl {
        url = "https://registry.npmjs.org/@actions/languageservice/-/languageservice-0.3.18.tgz";
        sha512 = "MvNpNlxiDsiif3/pVQG03MSbIqFNx+TXAKWooztiNoJfETxn/A1KH3w+6uMD5ckwKRBqcINOmsvzvLHnS0/BiA==";
      };
    };
    "@actions/workflow-parser-0.3.18" = {
      name = "_at_actions_slash_workflow-parser";
      packageName = "@actions/workflow-parser";
      version = "0.3.18";
      src = fetchurl {
        url = "https://registry.npmjs.org/@actions/workflow-parser/-/workflow-parser-0.3.18.tgz";
        sha512 = "jRimPU7hib7yjotp+pQhOjDvPVQcqckCdjGKMNAiZI/Qqnsp7G5oDlEwOn3VBln/4/RiaLBFzJWTLRzALs3wdg==";
      };
    };
    "@octokit/auth-token-3.0.4" = {
      name = "_at_octokit_slash_auth-token";
      packageName = "@octokit/auth-token";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/auth-token/-/auth-token-3.0.4.tgz";
        sha512 = "TWFX7cZF2LXoCvdmJWY7XVPi74aSY0+FfBZNSXEXFkMpjcqsQwDSYVv5FhRFaI0V1ECnwbz4j59T/G+rXNWaIQ==";
      };
    };
    "@octokit/auth-token-5.1.2" = {
      name = "_at_octokit_slash_auth-token";
      packageName = "@octokit/auth-token";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/auth-token/-/auth-token-5.1.2.tgz";
        sha512 = "JcQDsBdg49Yky2w2ld20IHAlwr8d/d8N6NiOXbtuoPCqzbsiJgF633mVUw3x4mo0H5ypataQIX7SFu3yy44Mpw==";
      };
    };
    "@octokit/core-4.2.4" = {
      name = "_at_octokit_slash_core";
      packageName = "@octokit/core";
      version = "4.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/core/-/core-4.2.4.tgz";
        sha512 = "rYKilwgzQ7/imScn3M9/pFfUf4I1AZEH3KhyJmtPdE2zfaXAn2mFfUy4FbKewzc2We5y/LlKLj36fWJLKC2SIQ==";
      };
    };
    "@octokit/core-6.1.6" = {
      name = "_at_octokit_slash_core";
      packageName = "@octokit/core";
      version = "6.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/core/-/core-6.1.6.tgz";
        sha512 = "kIU8SLQkYWGp3pVKiYzA5OSaNF5EE03P/R8zEmmrG6XwOg5oBjXyQVVIauQ0dgau4zYhpZEhJrvIYt6oM+zZZA==";
      };
    };
    "@octokit/endpoint-10.1.4" = {
      name = "_at_octokit_slash_endpoint";
      packageName = "@octokit/endpoint";
      version = "10.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/endpoint/-/endpoint-10.1.4.tgz";
        sha512 = "OlYOlZIsfEVZm5HCSR8aSg02T2lbUWOsCQoPKfTXJwDzcHQBrVBGdGXb89dv2Kw2ToZaRtudp8O3ZIYoaOjKlA==";
      };
    };
    "@octokit/endpoint-7.0.6" = {
      name = "_at_octokit_slash_endpoint";
      packageName = "@octokit/endpoint";
      version = "7.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/endpoint/-/endpoint-7.0.6.tgz";
        sha512 = "5L4fseVRUsDFGR00tMWD/Trdeeihn999rTMGRMC1G/Ldi1uWlWJzI98H4Iak5DB/RVvQuyMYKqSK/R6mbSOQyg==";
      };
    };
    "@octokit/graphql-5.0.6" = {
      name = "_at_octokit_slash_graphql";
      packageName = "@octokit/graphql";
      version = "5.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/graphql/-/graphql-5.0.6.tgz";
        sha512 = "Fxyxdy/JH0MnIB5h+UQ3yCoh1FG4kWXfFKkpWqjZHw/p+Kc8Y44Hu/kCgNBT6nU1shNumEchmW/sUO1JuQnPcw==";
      };
    };
    "@octokit/graphql-8.2.2" = {
      name = "_at_octokit_slash_graphql";
      packageName = "@octokit/graphql";
      version = "8.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/graphql/-/graphql-8.2.2.tgz";
        sha512 = "Yi8hcoqsrXGdt0yObxbebHXFOiUA+2v3n53epuOg1QUgOB6c4XzvisBNVXJSl8RYA5KrDuSL2yq9Qmqe5N0ryA==";
      };
    };
    "@octokit/openapi-types-18.1.1" = {
      name = "_at_octokit_slash_openapi-types";
      packageName = "@octokit/openapi-types";
      version = "18.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/openapi-types/-/openapi-types-18.1.1.tgz";
        sha512 = "VRaeH8nCDtF5aXWnjPuEMIYf1itK/s3JYyJcWFJT8X9pSNnBtriDf7wlEWsGuhPLl4QIH4xM8fqTXDwJ3Mu6sw==";
      };
    };
    "@octokit/openapi-types-24.2.0" = {
      name = "_at_octokit_slash_openapi-types";
      packageName = "@octokit/openapi-types";
      version = "24.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/openapi-types/-/openapi-types-24.2.0.tgz";
        sha512 = "9sIH3nSUttelJSXUrmGzl7QUBFul0/mB8HRYl3fOlgHbIWG+WnYDXU3v/2zMtAvuzZ/ed00Ei6on975FhBfzrg==";
      };
    };
    "@octokit/openapi-types-25.1.0" = {
      name = "_at_octokit_slash_openapi-types";
      packageName = "@octokit/openapi-types";
      version = "25.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/openapi-types/-/openapi-types-25.1.0.tgz";
        sha512 = "idsIggNXUKkk0+BExUn1dQ92sfysJrje03Q0bv0e+KPLrvyqZF8MnBpFz8UNfYDwB3Ie7Z0TByjWfzxt7vseaA==";
      };
    };
    "@octokit/plugin-paginate-rest-11.6.0" = {
      name = "_at_octokit_slash_plugin-paginate-rest";
      packageName = "@octokit/plugin-paginate-rest";
      version = "11.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/plugin-paginate-rest/-/plugin-paginate-rest-11.6.0.tgz";
        sha512 = "n5KPteiF7pWKgBIBJSk8qzoZWcUkza2O6A0za97pMGVrGfPdltxrfmfF5GucHYvHGZD8BdaZmmHGz5cX/3gdpw==";
      };
    };
    "@octokit/plugin-paginate-rest-6.1.2" = {
      name = "_at_octokit_slash_plugin-paginate-rest";
      packageName = "@octokit/plugin-paginate-rest";
      version = "6.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/plugin-paginate-rest/-/plugin-paginate-rest-6.1.2.tgz";
        sha512 = "qhrmtQeHU/IivxucOV1bbI/xZyC/iOBhclokv7Sut5vnejAIAEXVcGQeRpQlU39E0WwK9lNvJHphHri/DB6lbQ==";
      };
    };
    "@octokit/plugin-request-log-1.0.4" = {
      name = "_at_octokit_slash_plugin-request-log";
      packageName = "@octokit/plugin-request-log";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/plugin-request-log/-/plugin-request-log-1.0.4.tgz";
        sha512 = "mLUsMkgP7K/cnFEw07kWqXGF5LKrOkD+lhCrKvPHXWDywAwuDUeDwWBpc69XK3pNX0uKiVt8g5z96PJ6z9xCFA==";
      };
    };
    "@octokit/plugin-request-log-5.3.1" = {
      name = "_at_octokit_slash_plugin-request-log";
      packageName = "@octokit/plugin-request-log";
      version = "5.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/plugin-request-log/-/plugin-request-log-5.3.1.tgz";
        sha512 = "n/lNeCtq+9ofhC15xzmJCNKP2BWTv8Ih2TTy+jatNCCq/gQP/V7rK3fjIfuz0pDWDALO/o/4QY4hyOF6TQQFUw==";
      };
    };
    "@octokit/plugin-rest-endpoint-methods-13.5.0" = {
      name = "_at_octokit_slash_plugin-rest-endpoint-methods";
      packageName = "@octokit/plugin-rest-endpoint-methods";
      version = "13.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/plugin-rest-endpoint-methods/-/plugin-rest-endpoint-methods-13.5.0.tgz";
        sha512 = "9Pas60Iv9ejO3WlAX3maE1+38c5nqbJXV5GrncEfkndIpZrJ/WPMRd2xYDcPPEt5yzpxcjw9fWNoPhsSGzqKqw==";
      };
    };
    "@octokit/plugin-rest-endpoint-methods-7.2.3" = {
      name = "_at_octokit_slash_plugin-rest-endpoint-methods";
      packageName = "@octokit/plugin-rest-endpoint-methods";
      version = "7.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/plugin-rest-endpoint-methods/-/plugin-rest-endpoint-methods-7.2.3.tgz";
        sha512 = "I5Gml6kTAkzVlN7KCtjOM+Ruwe/rQppp0QU372K1GP7kNOYEKe8Xn5BW4sE62JAHdwpq95OQK/qGNyKQMUzVgA==";
      };
    };
    "@octokit/request-6.2.8" = {
      name = "_at_octokit_slash_request";
      packageName = "@octokit/request";
      version = "6.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/request/-/request-6.2.8.tgz";
        sha512 = "ow4+pkVQ+6XVVsekSYBzJC0VTVvh/FCTUUgTsboGq+DTeWdyIFV8WSCdo0RIxk6wSkBTHqIK1mYuY7nOBXOchw==";
      };
    };
    "@octokit/request-9.2.4" = {
      name = "_at_octokit_slash_request";
      packageName = "@octokit/request";
      version = "9.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/request/-/request-9.2.4.tgz";
        sha512 = "q8ybdytBmxa6KogWlNa818r0k1wlqzNC+yNkcQDECHvQo8Vmstrg18JwqJHdJdUiHD2sjlwBgSm9kHkOKe2iyA==";
      };
    };
    "@octokit/request-error-3.0.3" = {
      name = "_at_octokit_slash_request-error";
      packageName = "@octokit/request-error";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/request-error/-/request-error-3.0.3.tgz";
        sha512 = "crqw3V5Iy2uOU5Np+8M/YexTlT8zxCfI+qu+LxUB7SZpje4Qmx3mub5DfEKSO8Ylyk0aogi6TYdf6kxzh2BguQ==";
      };
    };
    "@octokit/request-error-6.1.8" = {
      name = "_at_octokit_slash_request-error";
      packageName = "@octokit/request-error";
      version = "6.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/request-error/-/request-error-6.1.8.tgz";
        sha512 = "WEi/R0Jmq+IJKydWlKDmryPcmdYSVjL3ekaiEL1L9eo1sUnqMJ+grqmC9cjk7CA7+b2/T397tO5d8YLOH3qYpQ==";
      };
    };
    "@octokit/rest-19.0.13" = {
      name = "_at_octokit_slash_rest";
      packageName = "@octokit/rest";
      version = "19.0.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/rest/-/rest-19.0.13.tgz";
        sha512 = "/EzVox5V9gYGdbAI+ovYj3nXQT1TtTHRT+0eZPcuC05UFSWO3mdO9UY1C0i2eLF9Un1ONJkAk+IEtYGAC+TahA==";
      };
    };
    "@octokit/rest-21.1.1" = {
      name = "_at_octokit_slash_rest";
      packageName = "@octokit/rest";
      version = "21.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/rest/-/rest-21.1.1.tgz";
        sha512 = "sTQV7va0IUVZcntzy1q3QqPm/r8rWtDCqpRAmb8eXXnKkjoQEtFe3Nt5GTVsHft+R6jJoHeSiVLcgcvhtue/rg==";
      };
    };
    "@octokit/tsconfig-1.0.2" = {
      name = "_at_octokit_slash_tsconfig";
      packageName = "@octokit/tsconfig";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/tsconfig/-/tsconfig-1.0.2.tgz";
        sha512 = "I0vDR0rdtP8p2lGMzvsJzbhdOWy405HcGovrspJ8RRibHnyRgggUSNO5AIox5LmqiwmatHKYsvj6VGFHkqS7lA==";
      };
    };
    "@octokit/types-10.0.0" = {
      name = "_at_octokit_slash_types";
      packageName = "@octokit/types";
      version = "10.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/types/-/types-10.0.0.tgz";
        sha512 = "Vm8IddVmhCgU1fxC1eyinpwqzXPEYu0NrYzD3YZjlGjyftdLBTeqNblRC0jmJmgxbJIsQlyogVeGnrNaaMVzIg==";
      };
    };
    "@octokit/types-13.10.0" = {
      name = "_at_octokit_slash_types";
      packageName = "@octokit/types";
      version = "13.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/types/-/types-13.10.0.tgz";
        sha512 = "ifLaO34EbbPj0Xgro4G5lP5asESjwHracYJvVaPIyXMuiuXLlhic3S47cBdTb+jfODkTE5YtGCLt3Ay3+J97sA==";
      };
    };
    "@octokit/types-14.1.0" = {
      name = "_at_octokit_slash_types";
      packageName = "@octokit/types";
      version = "14.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/types/-/types-14.1.0.tgz";
        sha512 = "1y6DgTy8Jomcpu33N+p5w58l6xyt55Ar2I91RPiIA0xCJBXyUAhXCcmZaDWSANiha7R9a6qJJ2CRomGPZ6f46g==";
      };
    };
    "@octokit/types-9.3.2" = {
      name = "_at_octokit_slash_types";
      packageName = "@octokit/types";
      version = "9.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/types/-/types-9.3.2.tgz";
        sha512 = "D4iHGTdAnEEVsB8fl95m1hiz7D5YiRdQ9b/OEb3BYRVwbLsGHcRVPz+u+BgRLNk0Q0/4iZCBqDN96j2XNxfXrA==";
      };
    };
    "before-after-hook-2.2.3" = {
      name = "before-after-hook";
      packageName = "before-after-hook";
      version = "2.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/before-after-hook/-/before-after-hook-2.2.3.tgz";
        sha512 = "NzUnlZexiaH/46WDhANlyR2bXRopNg4F/zuSA3OpZnllCUgRaOF2znDioDWrmbNVsuZk6l9pMquQB38cfBZwkQ==";
      };
    };
    "before-after-hook-3.0.2" = {
      name = "before-after-hook";
      packageName = "before-after-hook";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/before-after-hook/-/before-after-hook-3.0.2.tgz";
        sha512 = "Nik3Sc0ncrMK4UUdXQmAnRtzmNQTAAXmXIopizwZ1W1t8QmfJj+zL4OA2I7XPTPW5z5TDqv4hRo/JzouDJnX3A==";
      };
    };
    "cronstrue-2.61.0" = {
      name = "cronstrue";
      packageName = "cronstrue";
      version = "2.61.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cronstrue/-/cronstrue-2.61.0.tgz";
        sha512 = "ootN5bvXbIQI9rW94+QsXN5eROtXWwew6NkdGxIRpS/UFWRggL0G5Al7a9GTBFEsuvVhJ2K3CntIIVt7L2ILhA==";
      };
    };
    "deprecation-2.3.1" = {
      name = "deprecation";
      packageName = "deprecation";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/deprecation/-/deprecation-2.3.1.tgz";
        sha512 = "xmHIy4F3scKVwMsQ4WnVaS8bHOx0DmVwRywosKhaILI0ywMDWPtBSku2HNxRvF7jtwDRsoEwYQSfbxj8b7RlJQ==";
      };
    };
    "encoding-0.1.13" = {
      name = "encoding";
      packageName = "encoding";
      version = "0.1.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/encoding/-/encoding-0.1.13.tgz";
        sha512 = "ETBauow1T35Y/WZMkio9jiM0Z5xjHHmJ4XmjZOq1l/dXz3lr2sRn87nJy20RupqSh1F2m3HHPSp8ShIPQJrJ3A==";
      };
    };
    "fast-content-type-parse-2.0.1" = {
      name = "fast-content-type-parse";
      packageName = "fast-content-type-parse";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-content-type-parse/-/fast-content-type-parse-2.0.1.tgz";
        sha512 = "nGqtvLrj5w0naR6tDPfB4cUmYCqouzyQiz6C5y/LtcDllJdrcc6WaWW6iXyIIOErTa/XRybj28aasdn4LkVk6Q==";
      };
    };
    "iconv-lite-0.6.3" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.6.3.tgz";
        sha512 = "4fCk79wshMdzMp2rH06qWrJE4iolqLhCUH+OiuIgU++RB0+94NlDL81atO7GX55uUKueo0txHNtvEyI6D7WdMw==";
      };
    };
    "is-plain-object-5.0.0" = {
      name = "is-plain-object";
      packageName = "is-plain-object";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-plain-object/-/is-plain-object-5.0.0.tgz";
        sha512 = "VRSzKkbMm5jMDoKLbltAkFQ5Qr7VDiTFGXxYFXXowVj387GeGNOCsOH6Msy00SGZ3Fp84b1Naa1psqgcCIEP5Q==";
      };
    };
    "node-fetch-2.7.0" = {
      name = "node-fetch";
      packageName = "node-fetch";
      version = "2.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-fetch/-/node-fetch-2.7.0.tgz";
        sha512 = "c4FRfUm/dbcWZ7U+1Wq0AwCyFL+3nt2bEw05wfxSz+DWpWsitgmSgYmy2dQdWyKC1694ELPqMs/YzUSNozLt8A==";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha512 = "lNaJgI+2Q5URQBkccEKHTQOPaXdUxnZZElQTZY0MFUAuaEqe1E+Nyvgdz/aIyNi6Z9MzO5dv1H8n58/GELp3+w==";
      };
    };
    "safer-buffer-2.1.2" = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
      };
    };
    "tr46-0.0.3" = {
      name = "tr46";
      packageName = "tr46";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tr46/-/tr46-0.0.3.tgz";
        sha512 = "N3WMsuqV66lT30CrXNbEjx4GEwlow3v6rr4mCcv6prnfwhS01rkgyFdjPNBYd9br7LpXV1+Emh01fHnq2Gdgrw==";
      };
    };
    "typescript-5.9.2" = {
      name = "typescript";
      packageName = "typescript";
      version = "5.9.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/typescript/-/typescript-5.9.2.tgz";
        sha512 = "CWBzXQrc/qOkhidw1OzBTQuYRbfyxDXJMVJ1XNwUHGROVmuaeiEm3OslpZ1RV96d7SKKjZKrSJu3+t/xlw3R9A==";
      };
    };
    "universal-user-agent-6.0.1" = {
      name = "universal-user-agent";
      packageName = "universal-user-agent";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/universal-user-agent/-/universal-user-agent-6.0.1.tgz";
        sha512 = "yCzhz6FN2wU1NiiQRogkTQszlQSlpWaw8SvVegAc+bDxbzHgh1vX8uIe8OYyMH6DwH+sdTJsgMl36+mSMdRJIQ==";
      };
    };
    "universal-user-agent-7.0.3" = {
      name = "universal-user-agent";
      packageName = "universal-user-agent";
      version = "7.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/universal-user-agent/-/universal-user-agent-7.0.3.tgz";
        sha512 = "TmnEAEAsBJVZM/AADELsK76llnwcf9vMKuPz8JflO1frO8Lchitr0fNaN9d+Ap0BjKtqWqd/J17qeDnXh8CL2A==";
      };
    };
    "vscode-jsonrpc-8.1.0" = {
      name = "vscode-jsonrpc";
      packageName = "vscode-jsonrpc";
      version = "8.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-jsonrpc/-/vscode-jsonrpc-8.1.0.tgz";
        sha512 = "6TDy/abTQk+zDGYazgbIPc+4JoXdwC8NHU9Pbn4UJP1fehUyZmM4RHp5IthX7A6L5KS30PRui+j+tbbMMMafdw==";
      };
    };
    "vscode-jsonrpc-8.2.0" = {
      name = "vscode-jsonrpc";
      packageName = "vscode-jsonrpc";
      version = "8.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-jsonrpc/-/vscode-jsonrpc-8.2.0.tgz";
        sha512 = "C+r0eKJUIfiDIfwJhria30+TYWPtuHJXHtI7J0YlOmKAo7ogxP20T0zxB7HZQIFhIyvoBPwWskjxrvAtfjyZfA==";
      };
    };
    "vscode-languageserver-8.1.0" = {
      name = "vscode-languageserver";
      packageName = "vscode-languageserver";
      version = "8.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver/-/vscode-languageserver-8.1.0.tgz";
        sha512 = "eUt8f1z2N2IEUDBsKaNapkz7jl5QpskN2Y0G01T/ItMxBxw1fJwvtySGB9QMecatne8jFIWJGWI61dWjyTLQsw==";
      };
    };
    "vscode-languageserver-protocol-3.17.3" = {
      name = "vscode-languageserver-protocol";
      packageName = "vscode-languageserver-protocol";
      version = "3.17.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-protocol/-/vscode-languageserver-protocol-3.17.3.tgz";
        sha512 = "924/h0AqsMtA5yK22GgMtCYiMdCOtWTSGgUOkgEDX+wk2b0x4sAfLiO4NxBxqbiVtz7K7/1/RgVrVI0NClZwqA==";
      };
    };
    "vscode-languageserver-protocol-3.17.5" = {
      name = "vscode-languageserver-protocol";
      packageName = "vscode-languageserver-protocol";
      version = "3.17.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-protocol/-/vscode-languageserver-protocol-3.17.5.tgz";
        sha512 = "mb1bvRJN8SVznADSGWM9u/b07H7Ecg0I3OgXDuLdn307rl/J3A9YD6/eYOssqhecL27hK1IPZAsaqh00i/Jljg==";
      };
    };
    "vscode-languageserver-textdocument-1.0.12" = {
      name = "vscode-languageserver-textdocument";
      packageName = "vscode-languageserver-textdocument";
      version = "1.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-textdocument/-/vscode-languageserver-textdocument-1.0.12.tgz";
        sha512 = "cxWNPesCnQCcMPeenjKKsOCKQZ/L6Tv19DTRIGuLWe32lyzWhihGVJ/rcckZXJxfdKCFvRLS3fpBIsV/ZGX4zA==";
      };
    };
    "vscode-languageserver-types-3.17.3" = {
      name = "vscode-languageserver-types";
      packageName = "vscode-languageserver-types";
      version = "3.17.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-types/-/vscode-languageserver-types-3.17.3.tgz";
        sha512 = "SYU4z1dL0PyIMd4Vj8YOqFvHu7Hz/enbWtpfnVbJHU4Nd1YNYx8u0ennumc6h48GQNeOLxmwySmnADouT/AuZA==";
      };
    };
    "vscode-languageserver-types-3.17.5" = {
      name = "vscode-languageserver-types";
      packageName = "vscode-languageserver-types";
      version = "3.17.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-types/-/vscode-languageserver-types-3.17.5.tgz";
        sha512 = "Ld1VelNuX9pdF39h2Hgaeb5hEZM2Z3jUrrMgWQAu82jMtZp7p3vJT3BzToKtZI7NgQssZje5o0zryOrhQvzQAg==";
      };
    };
    "vscode-uri-3.1.0" = {
      name = "vscode-uri";
      packageName = "vscode-uri";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-uri/-/vscode-uri-3.1.0.tgz";
        sha512 = "/BpdSx+yCQGnCvecbyXdxHDkuk55/G3xwnC0GqY4gmQ3j+A+g8kzzgB4Nk/SINjqn6+waqw3EgbVF2QKExkRxQ==";
      };
    };
    "webidl-conversions-3.0.1" = {
      name = "webidl-conversions";
      packageName = "webidl-conversions";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/webidl-conversions/-/webidl-conversions-3.0.1.tgz";
        sha512 = "2JAn3z8AR6rjK8Sm8orRC0h/bcl/DqL7tRPdGZ4I1CjdF+EaMLmYxBHyXuKL849eucPFhvBoxMsflfOb8kxaeQ==";
      };
    };
    "whatwg-url-5.0.0" = {
      name = "whatwg-url";
      packageName = "whatwg-url";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/whatwg-url/-/whatwg-url-5.0.0.tgz";
        sha512 = "saE57nupxk6v3HY35+jzBwYa0rKSy0XR8JSxZPwgLr7ys0IBzhGviA1/TUGJLmSVqs8pb9AnvICXEuOHLprYTw==";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha512 = "l4Sp/DRseor9wL6EvV2+TuQn63dMkPjZ/sp9XkghTEbV9KlPS1xUsZ3u7/IQO4wxtcFB4bgpQPRcR3QCvezPcQ==";
      };
    };
    "yaml-2.8.1" = {
      name = "yaml";
      packageName = "yaml";
      version = "2.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/yaml/-/yaml-2.8.1.tgz";
        sha512 = "lcYcMxX2PO9XMGvAJkJ3OsNMw+/7FKes7/hgerGUYWIoWu5j/+YQqcZr5JnPZWzOsEBgMbSbiSTn/dv/69Mkpw==";
      };
    };
  };
in
{
  "@github/copilot-language-server" = nodeEnv.buildNodePackage {
    name = "_at_github_slash_copilot-language-server";
    packageName = "@github/copilot-language-server";
    version = "1.368.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/@github/copilot-language-server/-/copilot-language-server-1.368.0.tgz";
      sha512 = "az3ZFZzaynPGMXoXDVfN8S9CwRDXPJTr+gef0uyYmBGLoTCzuccn3tZkTxkopXqd4APpdC0K6pNnaHIwqw/dlA==";
    };
    dependencies = [
      sources."vscode-jsonrpc-8.2.0"
      sources."vscode-languageserver-protocol-3.17.5"
      sources."vscode-languageserver-types-3.17.5"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Your AI pair programmer";
      homepage = "https://github.com/github/copilot-language-server-release";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "@anthropic-ai/claude-code" = nodeEnv.buildNodePackage {
    name = "_at_anthropic-ai_slash_claude-code";
    packageName = "@anthropic-ai/claude-code";
    version = "1.0.111";
    src = fetchurl {
      url = "https://registry.npmjs.org/@anthropic-ai/claude-code/-/claude-code-1.0.111.tgz";
      sha512 = "1aALYgO8JyGtRdsFskB3uZiAUKbx8u2YcGoa55ZGwsczTBBVIy/+jsuOi3bAubqlBzi5/8gfFBwYK5QuA621MA==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Use Claude, Anthropic's AI assistant, right from your terminal. Claude can understand your codebase, edit files, run terminal commands, and handle entire workflows for you.";
      homepage = "https://github.com/anthropics/claude-code";
      license = "SEE LICENSE IN README.md";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  ccusage = nodeEnv.buildNodePackage {
    name = "ccusage";
    packageName = "ccusage";
    version = "16.2.3";
    src = fetchurl {
      url = "https://registry.npmjs.org/ccusage/-/ccusage-16.2.3.tgz";
      sha512 = "/BvsGfNjZ45SwSyzZy6xhQpwm2w8x2dp1yRGZql8115DQS3PNFNF9QJ+1YLMF0OayY/BU5R/mUQdd12DLekySQ==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Usage analysis tool for Claude Code";
      homepage = "https://github.com/ryoppippi/ccusage#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  gh-actions-language-server = nodeEnv.buildNodePackage {
    name = "gh-actions-language-server";
    packageName = "gh-actions-language-server";
    version = "0.0.3";
    src = fetchurl {
      url = "https://registry.npmjs.org/gh-actions-language-server/-/gh-actions-language-server-0.0.3.tgz";
      sha512 = "T2ph7OoS0tnpWsxpvdiC5k9rrv5t7BMwZRJANrk4gZzvTZ1/rY1kpJQjVaiYeTrlj2fDgQh5fMwPqkxNaKIGdw==";
    };
    dependencies = [
      sources."@actions/expressions-0.3.18"
      (
        sources."@actions/languageserver-0.3.18"
        // {
          dependencies = [
            sources."@octokit/rest-21.1.1"
          ];
        }
      )
      sources."@actions/languageservice-0.3.18"
      sources."@actions/workflow-parser-0.3.18"
      sources."@octokit/auth-token-5.1.2"
      (
        sources."@octokit/core-6.1.6"
        // {
          dependencies = [
            sources."@octokit/types-14.1.0"
          ];
        }
      )
      (
        sources."@octokit/endpoint-10.1.4"
        // {
          dependencies = [
            sources."@octokit/types-14.1.0"
          ];
        }
      )
      (
        sources."@octokit/graphql-8.2.2"
        // {
          dependencies = [
            sources."@octokit/types-14.1.0"
          ];
        }
      )
      sources."@octokit/openapi-types-25.1.0"
      (
        sources."@octokit/plugin-paginate-rest-11.6.0"
        // {
          dependencies = [
            sources."@octokit/openapi-types-24.2.0"
            sources."@octokit/types-13.10.0"
          ];
        }
      )
      sources."@octokit/plugin-request-log-5.3.1"
      (
        sources."@octokit/plugin-rest-endpoint-methods-13.5.0"
        // {
          dependencies = [
            sources."@octokit/openapi-types-24.2.0"
            sources."@octokit/types-13.10.0"
          ];
        }
      )
      (
        sources."@octokit/request-9.2.4"
        // {
          dependencies = [
            sources."@octokit/types-14.1.0"
          ];
        }
      )
      (
        sources."@octokit/request-error-6.1.8"
        // {
          dependencies = [
            sources."@octokit/types-14.1.0"
          ];
        }
      )
      (
        sources."@octokit/rest-19.0.13"
        // {
          dependencies = [
            sources."@octokit/auth-token-3.0.4"
            sources."@octokit/core-4.2.4"
            sources."@octokit/endpoint-7.0.6"
            sources."@octokit/graphql-5.0.6"
            sources."@octokit/openapi-types-18.1.1"
            sources."@octokit/plugin-paginate-rest-6.1.2"
            sources."@octokit/plugin-request-log-1.0.4"
            sources."@octokit/plugin-rest-endpoint-methods-7.2.3"
            sources."@octokit/request-6.2.8"
            sources."@octokit/request-error-3.0.3"
            sources."@octokit/types-10.0.0"
            sources."before-after-hook-2.2.3"
            sources."universal-user-agent-6.0.1"
          ];
        }
      )
      sources."@octokit/tsconfig-1.0.2"
      (
        sources."@octokit/types-9.3.2"
        // {
          dependencies = [
            sources."@octokit/openapi-types-18.1.1"
          ];
        }
      )
      sources."before-after-hook-3.0.2"
      sources."cronstrue-2.61.0"
      sources."deprecation-2.3.1"
      sources."encoding-0.1.13"
      sources."fast-content-type-parse-2.0.1"
      sources."iconv-lite-0.6.3"
      sources."is-plain-object-5.0.0"
      sources."node-fetch-2.7.0"
      sources."once-1.4.0"
      sources."safer-buffer-2.1.2"
      sources."tr46-0.0.3"
      sources."typescript-5.9.2"
      sources."universal-user-agent-7.0.3"
      sources."vscode-jsonrpc-8.1.0"
      sources."vscode-languageserver-8.1.0"
      (
        sources."vscode-languageserver-protocol-3.17.3"
        // {
          dependencies = [
            sources."vscode-languageserver-types-3.17.3"
          ];
        }
      )
      sources."vscode-languageserver-textdocument-1.0.12"
      sources."vscode-languageserver-types-3.17.5"
      sources."vscode-uri-3.1.0"
      sources."webidl-conversions-3.0.1"
      sources."whatwg-url-5.0.0"
      sources."wrappy-1.0.2"
      sources."yaml-2.8.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "**GitHub Actions Language Server**";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
