[[plugins]]
repo = 'Shougo/dpp.vim'
# rtp = ''
hook_add = '''
command! DppUpdate call dpp#async_ext_action('installer', 'update')
command! DppInstall call dpp#async_ext_action('installer', 'install')
command! DppCheckNotUpdated call dpp#async_ext_action('installer', 'checkNotUpdated')
command! DppMakeState call DppMakeState()
'''

# extension
[[plugins]]
repo = 'Shougo/dpp-ext-lazy'
on_source = 'dpp.vim'
# rtp = ''
[[plugins]]
repo = 'Shougo/dpp-ext-toml'
on_source = 'dpp.vim'
hook_add = '''
autocmd MyAutoCmd CursorHold */rc/*.toml call dpp#ext#toml#syntax()
'''
[[plugins]]
repo = 'Shougo/dpp-ext-local'
on_source = 'dpp.vim'
[[plugins]]
repo = 'Shougo/dpp-ext-installer'
on_source = 'dpp.vim'

# protocol
[[plugins]]
repo = 'Shougo/dpp-protocol-git'
on_source = 'dpp.vim'

