[[plugins]]
repo = 'sainnhe/everforest'
on_event = ['VimEnter', 'BufRead']
hook_add = '''
let g:everforest_background = 'hard'
let g:everforest_better_performance = 1
'''
hook_source = '''
colorscheme everforest
" highlight Normal guibg=NONE
" highlight NormalNC guibg=NONE
'''
