#! /usr/bin/env bash
# シンボリックリンクの作成

set -e

DIR=$(dirname "$0")
cd "$DIR"

# load util function
. ./utils/functions.sh

cd "../"
SOURCE="$(realpath -m .)"
DESTINATION="$(realpath -m ~)"

info "Make shimlinks"

[ ! -d "$HOME/.config" ] && mkdir "$HOME/.config"

# git
symlink "$SOURCE/git/.gitconfig" "$DESTINATION/.gitconfig"
symlink "$SOURCE/git/.gitmessage" "$DESTINATION/.gitmessage"
# fish
symlink "$SOURCE/fish" "$DESTINATION/.config/fish"
# neovim
symlink "$SOURCE/nvim" "$DESTINATION/.config/nvim"
# starship
symlink "$SOURCE/starship" "$DESTINATION/.config/starship"
# node
symlink "$SOURCE/node/.default-npm-packages" "$DESTINATION/.default-npm-packages"
# wezterm
symlink "$SOURCE/wezterm" "$DESTINATION/.config/wezterm"
# alactirry
symlink "$SOURCE/alacritty" "$DESTINATION/.config/alacritty"
# ideavim
symlink "$SOURCE/jetbrains/.ideavimrc" "$DESTINATION/.ideavimrc"
symlink "$SOURCE/gh" "$DESTINATION/.config/gh"
symlink "$SOURCE/gh-dash" "$DESTINATION/.config/gh-dash"
symlink "$SOURCE/markdownlint" "$DESTINATION/.config/markdownlint"
symlink "$SOURCE/lazygit" "$DESTINATION/.config/lazygit"
symlink "$SOURCE/efm-langserver" "$DESTINATION/.config/efm-langserver"

if [ "$(uname)" == 'Darwin' ]; then
  # asdf
  symlink "$SOURCE/asdf/darwin/.tool-versions" "$DESTINATION/.tool-versions"
  # zsh
  symlink "$SOURCE/shell/.zshrc" "$DESTINATION/.zshrc"
  # navi
  symlink "$SOURCE/navi" "$DESTINATION/.config/navi"
elif [ "$(uname)" == 'Linux' ]; then
  # asdf
  symlink "$SOURCE/asdf/linux/.tool-versions"  "$DESTINATION/.tool-versions"
  # i3
  symlink "$SOURCE/i3"                         "$DESTINATION/.config/i3"
  symlink "$SOURCE/i3blocks"                   "$DESTINATION/.config/i3blocks"
  # shell
  symlink "$SOURCE/shell/.bashrc"              "$DESTINATION/.bashrc"
  symlink "$SOURCE/shell/.profile"             "$DESTINATION/.profile"
fi

success "Finished"
