#! /usr/bin/env bash
# シンボリックリンクの作成

set -e

DIR=$(dirname "$0")
cd "$DIR"

# load util function
. ./utils/functions.sh

cd "../"
SOURCE="$(realpath -m .)"
DESTINATION="$(realpath -m ~)"

info "Make shimlinks"

[ ! -d "$HOME/.config" ] && mkdir "$HOME/.config"

symlink "$SOURCE/git/.gitconfig" "$DESTINATION/.gitconfig"
# symlink "$SOURCE/tmux/.tmux.conf" "$DESTINATION/.tmux.conf"
symlink "$SOURCE/fish" "$DESTINATION/.config/fish"
symlink "$SOURCE/nvim" "$DESTINATION/.config/nvim"
symlink "$SOURCE/starship" "$DESTINATION/.config/starship"
symlink "$SOURCE/node/.default-npm-packages" "$DESTINATION/.default-npm-packages"
# wezterm
symlink "$SOURCE/config/wezterm" "$DESTINATION/.config/wezterm"
symlink "$SOURCE/config/.ideavimrc" "$DESTINATION/.ideavimrc"

if [ "$(uname)" == 'Darwin' ]; then
  symlink "$SOURCE/asdf/darwin/.tool-versions" "$DESTINATION/.tool-versions"
  symlink "$SOURCE/shell/.zshrc" "$DESTINATION/.zshrc"
  symlink "$SOURCE/navi" "$DESTINATION/.config/navi"
elif [ "$(uname)" == 'Linux' ]; then
  symlink "$SOURCE/asdf/linux/.tool-versions"  "$DESTINATION/.tool-versions"
  symlink "$SOURCE/i3"                         "$DESTINATION/.config/i3"
  symlink "$SOURCE/i3blocks"                   "$DESTINATION/.config/i3blocks"
  symlink "$SOURCE/shell/.bashrc"              "$DESTINATION/.bashrc"
  symlink "$SOURCE/shell/.profile"             "$DESTINATION/.profile"
fi

success "Finished"
