approval_policy = "on-request"
sandbox_mode = "workspace-write"
web_search = "cached"
model_reasoning_effort = "medium"
personality = "pragmatic"
project_doc_fallback_filenames = [ "CLAUDE.md" ]
project_doc_max_bytes = 65536
notify = [ "/Users/s34580/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient", "turn-ended" ]
model = "gpt-5.6-sol"
service_tier = "priority"

[agents]
max_threads = 3

[features]
hooks = true
multi_agent = true
shell_snapshot = true
memories = true
js_repl = false

[sandbox_workspace_write]
network_access = true

[desktop]
followUpQueueMode = "queue"
dock-icon-preference = "app-default"
mac-menu-bar-enabled = false

[projects."/Users/s34580/ghq/github.com/abema/abema-android"]
trust_level = "trusted"

[projects."/Users/s34580/dotfiles"]
trust_level = "trusted"

[projects."/Users/s34580/ghq/github.com/mikanIchinose/github-notifier"]
trust_level = "trusted"

[projects."/Users/s34580/ghq/github.com/abema/abema-native"]
trust_level = "trusted"

[marketplaces.openai-bundled]
last_updated = "2026-07-13T03:07:32Z"
source_type = "local"
source = "/Users/s34580/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
last_updated = "2026-07-10T03:03:12Z"
source_type = "local"
source = "/Users/s34580/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[plugins."sites@openai-bundled"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[plugins."visualize@openai-bundled"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."template-creator@openai-primary-runtime"]
enabled = true

[mcp_servers.node_repl]
args = []
command = "/Applications/Codex.app/Contents/Resources/cua_node/bin/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = "/Applications/Codex.app/Contents/Resources/cua_node/lib/node_modules"
NODE_REPL_NODE_PATH = "/Applications/Codex.app/Contents/Resources/cua_node/bin/node"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/s34580/.codex"
CODEX_HOME = "/Users/s34580/.codex"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "6d25aa7656feac858f3a3bdaea5bcbab0dbfd426c9de8e6931ce90c399ee8e4f,f8b28403a0497b2e0bed024969fa474bb1f564509a59993449924c4ecab9db0d"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative."
NODE_REPL_INSTRUCTIONS_USE_CASE_COMPUTER_USE = "Control desktop apps on macOS through Computer Use."
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.707.61608"
CODEX_CLI_PATH = "/Applications/Codex.app/Contents/Resources/codex"

[mcp_servers.computer-use]
command = "./Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient"
args = [ "mcp" ]
cwd = "."
enabled = false

[mcp_servers.pencil]
command = "/Applications/Pencil.app/Contents/Resources/app.asar.unpacked/out/mcp-server-darwin-arm64"
args = [ "--app", "desktop", "--agent", "codexCLI" ]

[tui.model_availability_nux]
"gpt-5.5" = 4
"gpt-5.6-sol" = 4
